// app/layout.tsx
import type { Metadata } from "next";
import "../globals.css";

import { ThemeProvider } from "@/components/theme";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PassportLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
     <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      {children}
      <Toaster />
    </ThemeProvider>
  );
}
